# Build backend configuration
[build-system]
requires = [
    "setuptools>=61.0",  # Modern setuptools version
    "wheel"              # Required to build wheels
]
build-backend = "setuptools.build_meta"

# Project metadata
[project]
name = "vworld"   # Package name on PyPI
version = "0.0.0"        # Increase each release
description = "webots api"
readme = "README.md"     # Long description for PyPI
license = {file = "LICENSE"}
authors = [
  {name = "Muaz Alamri", email = "muazalamri2006@gmail.com"}  # Author info
]

requires-python = ">=3.8"  # Minimum Python version supported

# Runtime dependencies
dependencies = [
]

# Useful project links for PyPI
[project.urls]
Homepage = "https://github.com/ROBOTSdb/vworld"
Documentation = "https://github.com/ROBOTSdb/vworld#readme"
Source = "https://github.com/ROBOTSdb/vworld"
Issues = "https://github.com/ROBOTSdb/vworld/issues"
